<?php
/**
 * Smartcoin payment method model
 *
 * @category    Smartcoin
 * @package     Smartcoin_Checkout
 * @author      Arthur Granado <agranado@smartcoin.com.br>
 * @copyright   Smartcoin (https://smartcoin.com.br)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?>

<br />
<span>information(apagar)<?php echo $this->getSmartcoinBankSlipBarCode(); ?></span>
<br />
<a href="<?php echo $this->getSmartcoinBankSlipLink(); ?>" target="_blank"><?php echo $this->__('Click here to print your Bank Slip') ?></a>

<?php echo $this->getChildHtml()?>
