<?php
/**
 * Smartcoin payment method model
 *
 * @category    Smartcoin
 * @package     Smartcoin_Checkout
 * @author      Arthur Granado <agranado@smartcoin.com.br>
 * @copyright   Smartcoin (https://smartcoin.com.br)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$customer=Mage::getSingleton('customer/session');
$billingaddress = Mage::getModel('customer/address')->load($customer->getCustomer()->default_billing);
$addressdata = $billingaddress->getData();
$order = Mage::getModel("sales/order")->load($order_id);

$customerEmail = '';
$customerAddress = '';
$customerCity = '';
$customerState = '';
$customerCep = '';
$customerCountry = '';

if($customer->isLoggedIn()) {
    $customerEmail = $customer->getCustomer()->getEmail();
}

if($addressdata)
  Mage::log('Shipment Address: ' . json_encode($addressdata));
?>
<script type="text/javascript">
Payment.prototype._save = Payment.prototype.save;
Payment.prototype.save = function() {
    if (checkout.loadWaiting!=false) return;
    var validator = new Validation(this.form);
    if (this.validate() && validator.validate()) {
        this._save();
    }
};

Review.prototype._save = Review.prototype.save;
Review.prototype.save = function() {
  $j = jQuery.noConflict();
  if (payment.currentMethod == 'smartcoin_smartcheckout_cc') {
    checkout.setLoadWaiting('review');
    params = {
        <?php if($customer->isLoggedIn()) { ?>
            email: '<?php echo $customer->getCustomer()->getEmail(); ?>',
        <?php } else { ?>
            email: $j('#billing\\:email').val(),
        <?php } ?>
      card: { 
        number: $j('input[data-smartcoin="number"]').val().replace(/\s*/g, ""),
        name: $j('input[data-smartcoin="name"]').val(),
        exp_month: $j('select[data-smartcoin="exp_month"]').val(),
        exp_year: $j('select[data-smartcoin="exp_year"]').val(),
        cvc: $j('input[data-smartcoin="cvc"]').val(),
        <?php if($customer->isLoggedIn()) { ?>
          address_line_1: '<?php echo str_replace("\n",' ', $addressdata["street"]); ?>',
          address_city: '<?php echo $addressdata["city"]; ?>',
          address_state: '<?php echo $addressdata["region"]; ?>',
          address_cep: '<?php echo $addressdata["postcode"]; ?>',
          address_country: '<?php echo $addressdata["country_id"]; ?>',
        <?php } else { ?>
          address_line_1: $j('#billing\\:stree1').val(),
          address_city: $j('#billing\\:city').val(),
          address_state: $j('#billing\\:region_id').val(),
          address_cep: $j('#billing\\:postcode').val(),
          address_country: $j('#billing\\:country_id').val(),
        <?php } ?>
      }
    };

    SmartCoin.set_api_key(_smartcoin_api_key);
    SmartCoin.create_customer(params, function(data){
      checkout.setLoadWaiting(false);
      if (data.id) {
        $j('form#co-payment-form').append('<input type="hidden" id="smartcoin_smartcheckout_cc_smartcoin_customer" name="payment[smartcoin_customer]" value="' + data.id + '" />');
        this._save();
      } else {
        alert(JSON.stringify(data.errors));
      }
    }.bind(this));
  } else {
    this._save();
  }
};
</script>
