<?php
/**
 * Smartcoin payment method model
 *
 * @category    Smartcoin
 * @package     Smartcoin_Checkout
 * @author      Arthur Granado <agranado@smartcoin.com.br>
 * @copyright   Smartcoin (https://smartcoin.com.br)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">
  var _smartcoin_api_key = '<?php echo Mage::helper('smartcoin_smartcheckout')->getApiKey(); ?>';

  var headTag = document.getElementsByTagName("head")[0];
  var smartTag = document.createElement('script');
  smartTag.type = 'text/javascript';
  smartTag.async = false;
  smartTag.src = 'https://js.smartcoin.com.br/v1/smartcoin.js';
  headTag.appendChild(smartTag);
</script>